##  NMF (Non-Negative Matric Factorization, 음수 미포함 행렬 분해)

In [1]:
import pandas as pd
npr = pd.read_csv('npr.csv')
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [2]:
npr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11992 entries, 0 to 11991
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Article  11992 non-null  object
dtypes: object(1)
memory usage: 93.8+ KB


### Text Preprocessing

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
# max_df(threshold), min_df(theshold) -> 0.0 ~ 0.1 or int (default 1)
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [5]:
dtm = tfidf.fit_transform(npr['Article'])

In [6]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [7]:
# NMF (토픽 모델링의 대표 알고리즘)
from sklearn.decomposition import NMF

In [8]:
NMF = NMF(n_components=7, random_state=42) # n_components -> topic count

In [9]:
NMF.fit(dtm)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/decomposition/_nmf.py:289: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  warnings.warn(


NMF(n_components=7, random_state=42)

In [10]:
len(tfidf.get_feature_names())

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


54777

In [12]:
import random

for i in range(10):
    random_word_id = random.randint(0, 54776)
    print(tfidf.get_feature_names()[random_word_id])

amite
disbelieving
plundered
politburo
salaried
strummed
authorship
doctorate
sprained
enforcer


In [13]:
for i in range(10):
    random_word_id = random.randint(0, 54776)
    print(tfidf.get_feature_names()[random_word_id])

meyerson
tightest
comp
wisc
luigi
trained
flanked
pasture
favors
additional


In [14]:
len(NMF.components_)

7

In [16]:
NMF.components_

array([[0.00000000e+00, 2.49950821e-01, 0.00000000e+00, ...,
        1.70313822e-03, 2.37544362e-04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.22048918e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 3.12379960e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.89723338e-03, 0.00000000e+00, 1.50186440e-03, ...,
        7.06428924e-04, 5.85500542e-04, 6.89536542e-04],
       [4.01763234e-03, 5.31643833e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [17]:
len(NMF.components_[0])

54777

In [18]:
single_topic = NMF.components_[0]

In [19]:
single_topic

array([0.00000000e+00, 2.49950821e-01, 0.00000000e+00, ...,
       1.70313822e-03, 2.37544362e-04, 0.00000000e+00])

In [20]:
single_topic.argsort()

array([    0, 27208, 27206, ..., 36283, 54692, 42993])

In [21]:
single_topic[2475]

0.0

In [22]:
single_topic[18302]

0.0

In [23]:
single_topic[42993]

2.0050551654185824

In [24]:
single_topic.argsort()[-10:]

array([14441, 36310, 53989, 52615, 47218, 53152, 19307, 36283, 54692,
       42993])

In [25]:
top_word_indices = single_topic.argsort()[-10:]

In [26]:
for index in top_word_indices:
    print(tfidf.get_feature_names()[index])

disease
percent
women
virus
study
water
food
people
zika
says


In [27]:
for index, topic in enumerate(NMF.components_):
    print(f'TOPIC #{index}')
    print([tfidf.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

TOPIC #0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


TOPIC #1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


TOPIC #2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


TOPIC #3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


TOPIC #4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


TOPIC #5
['love', 've', 'don', 'album', 'way', 'time', 'song', 'life', 'really', 'know', 'people', 'think', 'just', 'music', 'like']


TOPIC #6
['teacher', 'sta

In [28]:
dtm.shape

(11992, 54777)

In [29]:
len(npr)

11992

In [32]:
topic_results = NMF.transform(dtm)
topic_results.shape

(11992, 7)

In [33]:
topic_results[10]

array([0.00100452, 0.        , 0.00149598, 0.        , 0.        ,
       0.06031492, 0.        ])

In [34]:
topic_results[10].round(2)

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.06, 0.  ])

In [35]:
topic_results[10].argmax()

5

In [36]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [37]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3])

In [38]:
npr['Topic'] = topic_results.argmax(axis=1)

In [39]:
npr.head(10)

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      3
4  From photography, illustration and video, to d...      6
5  I did not want to join yoga class. I hated tho...      5
6  With a   who has publicly supported the debunk...      0
7  I was standing by the airport exit, debating w...      0
8  If movies were trying to be more realistic, pe...      0
9  Eighteen years ago, on New Year’s Eve, David F...      5