##  LDA (Latent Dirichlet Allocation, 잠재적 드리클레 할당)

In [1]:
import pandas as pd
npr = pd.read_csv('npr.csv')
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [2]:
npr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11992 entries, 0 to 11991
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Article  11992 non-null  object
dtypes: object(1)
memory usage: 93.8+ KB


### Text Preprocessing

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
# max_df(threshold), min_df(theshold) -> 0.0 ~ 0.1 or int (default 1)
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [7]:
dtm = cv.fit_transform(npr['Article'])

In [8]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [9]:
# LDA (토픽 모델링의 대표 알고리즘)
from sklearn.decomposition import LatentDirichletAllocation

In [13]:
LDA = LatentDirichletAllocation(n_components=7, random_state=42) # n_components -> topic count

In [14]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [17]:
len(cv.get_feature_names())

54777

In [18]:
import random

for i in range(10):
    random_word_id = random.randint(0, 54776)
    print(cv.get_feature_names()[random_word_id])

mordecai
photojournalism
retraining
ut
motherly
baths
fizzles
shamed
promo
lecuona


In [19]:
for i in range(10):
    random_word_id = random.randint(0, 54776)
    print(cv.get_feature_names()[random_word_id])

elife
balm
verdicts
reprisal
rabbis
manipulated
plata
bunkers
diseases
reconfirm


In [23]:
len(LDA.components_)

7

In [24]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [25]:
len(LDA.components_[0])

54777

In [26]:
single_topic = LDA.components_[0]

In [27]:
single_topic

array([8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
       1.43006821e-01, 1.42902042e-01, 1.42861626e-01])

In [28]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [29]:
single_topic[2475]

0.1428571430851871

In [30]:
single_topic[18302]

0.14285714309286987

In [31]:
single_topic[42993]

6247.245510521079

In [32]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [33]:
top_word_indices = single_topic.argsort()[-10:]

In [35]:
for index in top_word_indices:
    print(cv.get_feature_names()[index])

new
percent
government
company
million
care
people
health
said
says


In [36]:
for index, topic in enumerate(LDA.components_):
    print(f'TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', 'like']


TOPIC #6
['student', 'years', 'data', 'science', 'university', 'people', 'time', 'schools', 'just

In [37]:
dtm.shape

(11992, 54777)

In [38]:
len(npr)

11992

In [41]:
topic_results = LDA.transform(dtm)
topic_results.shape

(11992, 7)

In [48]:
topic_results[10]

array([3.11715739e-04, 3.11608897e-04, 1.28203518e-01, 6.10510543e-02,
       3.11745679e-04, 8.09498736e-01, 3.11621414e-04])

In [49]:
topic_results[10].round(2)

array([0.  , 0.  , 0.13, 0.06, 0.  , 0.81, 0.  ])

In [50]:
topic_results[10].argmax()

5

In [51]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [52]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0])

In [53]:
npr['Topic'] = topic_results.argmax(axis=1)

In [54]:
npr.head(10)

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2
5  I did not want to join yoga class. I hated tho...      3
6  With a   who has publicly supported the debunk...      3
7  I was standing by the airport exit, debating w...      2
8  If movies were trying to be more realistic, pe...      3
9  Eighteen years ago, on New Year’s Eve, David F...      2